# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.runs/synth_1/ccnn_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 2
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu3eg-sbva484-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.cache/wt [current_project]
set_property parent.project_path C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/wwwka/Desktop/my_cnn/the_ip/the_controller_axi_1.0
  c:/Users/wwwka/Desktop/my_cnn/denoise/iprepo
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/Users/wwwka/Desktop/my_cnn/denoise/denoise_ram/input_l8_p6.coe
add_files C:/Users/wwwka/Desktop/my_cnn/denoise/denoise_ram/single_conv_wb_wp6_bp12.coe
read_verilog -library xil_defaultlib {
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/lib_dnotop.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/acc_post.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/accumulator.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/lib_conv.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/conv.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/conv_rp.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/ddr_read_write.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/lib_dw_block.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/dw_block.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/main_con.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/mul_array.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/pre_cal.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/pre_cal_d.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/pre_cal_w.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/lib_rb.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/result_block.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/syn_data_fifo.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/hdl/system_wrapper.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/weight.v
  C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/new/ccnn_top.v
}
add_files C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_rst_ps8_0_213M_1/system_rst_ps8_0_213M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_rst_ps8_0_213M_1/system_rst_ps8_0_213M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_rst_ps8_0_213M_1/system_rst_ps8_0_213M_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/ip/weight_inc_0_conv/weight_inc_0_conv.xci
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/weight_inc_0_conv/weight_inc_0_conv_ooc.xdc]

read_ip -quiet C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/ip/result/result.xci
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/result/result_ooc.xdc]

read_ip -quiet C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/ip/fifo_dram/fifo_dram.xci
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/fifo_dram/fifo_dram.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/fifo_dram/fifo_dram_ooc.xdc]

read_ip -quiet C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/constrs_1/new/cons.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ccnn_top -part xczu3eg-sbva484-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ccnn_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ccnn_top_utilization_synth.rpt -pb ccnn_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
