# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/wwwka/Desktop/my_cnn/denoise/denoise.srcs/sources_1/ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wwwka/Desktop/my_cnn/denoise/denoise.gen/sources_1/ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
